filepath: '/media/sf_VMShare/ModelMapping/'
mappingfile: 'CCDI_v3.1.0-CDS_v10.0.0.tsv'
mismatchfile: 'CCDI_v3.1.0-CDS_v10.0.0_MISMATCH_REPORT.tsv'
#mismatchfile: 'CDS_v9.0.0-CDS_v10.0.0_Cleanup.csv'
savefile: 'CCDI_v3.1.0-CDS_v10.0.0_DEMISMATCHED.tsv'