filepath: '/media/sf_VMShare/IDCModel/'
mappingfile: 'IDC_0.0.1-CDS_v10.0.0.tsv'
mismatchfile: 'IDC_0.0.1-CDS_v10.0.0_MISMATCH_REPORT.tsv'
#mismatchfile: 'CDS_v9.0.0-CDS_v10.0.0_Cleanup.csv'
savefile: 'IDC_0.0.1-CDS_v10.0.0_DEMISMATCHED.tsv'